version: '3'
services:

  backend:
    build:
      context: ./
      dockerfile: backend.dockerfile
    container_name: backend
    volumes:
      - ./backend:/home/app
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/home/app
    ports:
      - "3000:3000"

  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"


  email-service:
    build:
      context: ./
      dockerfile: email.dockerfile
    container_name: email-service
    volumes:
      - ./email-service:/home/app

volumes:
  rabbitmq_data: